# Generated by Django 4.0 on 2022-01-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_image',
            name='Ans',
            field=models.TextField(default=' '),
        ),
    ]
