# Generated by Django 4.0 on 2022-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_show_image_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_image',
            name='Student_name',
            field=models.CharField(max_length=200),
        ),
    ]
