# Generated by Django 4.0 on 2022-01-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Admin_app', '0004_alter_show_image_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_image',
            name='Student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
