# Generated by Django 4.0 on 2022-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_alter_show_image_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_image',
            name='Ans',
            field=models.CharField(max_length=200),
        ),
    ]
