# Generated by Django 4.0 on 2022-01-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0006_alter_show_image_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show_image',
            old_name='attechment',
            new_name='Attechment',
        ),
        migrations.RenameField(
            model_name='show_image',
            old_name='Disc',
            new_name='Student_Disc',
        ),
        migrations.RenameField(
            model_name='show_image',
            old_name='Student_name',
            new_name='Student_Name',
        ),
    ]
