# Generated by Django 4.0 on 2022-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0007_rename_attechment_show_image_attechment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show_image',
            name='Ans',
        ),
        migrations.AddField(
            model_name='show_image',
            name='Answer',
            field=models.TextField(default=''),
        ),
    ]
