# Generated by Django 4.0 on 2022-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0008_remove_show_image_ans_show_image_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_image',
            name='Student_Name',
            field=models.CharField(max_length=200),
        ),
    ]
